#!/usr/bin/env node
import { writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { readSection } from './lib/content.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUT_DIR = join(ROOT, 'assets', 'js');

export const SECTIONS = [
  { dir: 'posts',    key: 'posts',    urlPrefix: 'blog',     out: 'posts.js' },
  { dir: 'research', key: 'research', urlPrefix: 'research', out: 'research.js' },
];

export function build({ quiet = false } = {}) {
  mkdirSync(OUT_DIR, { recursive: true });
  const summary = [];

  for (const section of SECTIONS) {
    const { items, drafts } = readSection({ dir: join(ROOT, section.dir), urlPrefix: section.urlPrefix });

    // U+2028 and U+2029 are legal inside a JSON string but end a line in JS source.
    const SEPS = new RegExp(String.fromCharCode(91, 0x2028, 0x2029, 93), 'g');
    const json = JSON.stringify(items, null, 2).replace(SEPS, function (ch) {
      return String.fromCharCode(92) + 'u' + ch.charCodeAt(0).toString(16);
    });

    writeFileSync(join(OUT_DIR, section.out),
      '// Generated by scripts/build-content.mjs. Do not edit; edit ' + section.dir + '/*.md instead.\n' +
      'SITE.' + section.key + ' = ' + json + ';\n');

    summary.push(section.dir + ': ' + items.length + ' published, ' + drafts + ' draft');
  }

  if (!quiet) console.log(summary.join('  |  '));
  return summary;
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  try {
    build();
  } catch (e) {
    console.error('\nbuild-content failed:\n  ' + e.message + '\n');
    process.exit(1);
  }
}
